language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: YPQIG2QbV1OUwfe0lwnJtvEhkP7mIeNJynBbhOHr4g8HVzn6Lkf3tdmE6aAJ5kWoepEwtEgz/g0efnB123ZXGbdSc8pOE4b8lPFNEdXNdrfLyora3ROuqngXQeYEQ8kCmI6zlhcaPmdUgigeAeDMrWe8Wi/6G7HF10HTK60FgIXiD9/FNvr+7InTexCBS8WbnQbOXqb5QQSoUK3vJMbyZYhxBbfxGrOiDdS2U9VcMz3EX+t6eSP4+VYv0SlUuCd6xTS/lREw7OCcd/BeEcvRQaJRhrVNzFvpgKUluUG9NExpZYw5ExDjsXiuX1iStEWIwWkrDW1pWytIBml+byroafzD+SmH+iIlRWHWf3hMi+Hcswt6ktrBJra9le64YO3rjGy/Gl+fpQI2iy9YY/vTpCuGryO/FWpeouFQJSDKYFADiw4LVyo4x4RigIPugeml3bkB+A+4M/pefS9XzG/ppM/oVHwteGtv1h/kzDDYThKz9xD3UIYVvDNyUKWG9CeLj9yrU6mp3f5eihrjhxRfVV5eqLaEeybhyILDXf/EuMED2ZFOTTGdXsYS8iMKls9Q4AFA0zc054aCcWTdwWMMMMTf/6AoB75zMezdPg/ZaHOMWoBtJzJlfYIpVHJueA96C5TYTAq44oK/VDGqbiNRgN+irZwY+fw+d0UkYxJwTwM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: hoverboard
  token:
    secure: "VuEoW5iQb7I4RmLWAa79+NCkYi8ByPCjM/aSaL7MzSaguI07i/g3D1XeciuSJITKfK7Y6+ww6KSaYU9c2kIPpGqH7w4ES7DUQU9it296U1gJrIQ84F7XwZZDHUScfc5vHRUWroqCJrAKuDsvmtOAWB+CD+pBLJQcCWG8JFRKmny/3GcEczesJh40pVsKtG91ZX/VDWVRmIngzqwzDHkytUnIgysyoWdHQ3AfpuW5J2vsR/apeYgz+Srbifbx2TwardaxIu+crEA1BegrWvV6sUOZlK7xsKSRKcAwxTCGAk/F0EqD6JJ8teueZXU35PDygQLeiNnjAV/VulV/7nTEO4cqzPy2jydfjJaciE3SEM8fkoij9NeyGm0izYSqm4jy9ivbVgn5vBk3NTERYKm9mSyU9jB1Ov3y1f+i/kPHE388B1sB9p7DKa+1kyzSufXvqT8xXr2oL20BmaHz5cobjwv6CQWZGN6KtyRXUetIk1luQNkHZLhZNEszTe/H5MJYlkk/nntzviAHMOlylqeQe/xFG49NUY0TGcKi/7gTuHD29Qy0dTuWlBxBvJ5sUxLIAH9RCWT1bXhtCDoYkCC3qOHc/fcQOYOCbjDXUpE1b79qLVHcDkqNltKVaMGt3FnnZNjb2gqG8eVJJAuSQ93+VyzrBAKCENDoTedZSKnkaMs="
